/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc.seng301.cardbattler.asg3;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Assertions.assertTrue(true);
    }
}
